name: CI/CD pipeline
run-name: microservices

on: 
  push:
    branches:
      - main

jobs:
  client-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Checking
      run: |
       echo "Hello"
       echo "World"

  server-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js for server
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies for server
      working-directory: ./backend
      run: npm install
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'javascript'

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
